# coding: utf-8

"""
    Web of Science API Lite

    A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Author(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authors': 'list[str]',
        'book_authors': 'list[str]',
        'book_group_authors': 'list[str]'
    }

    attribute_map = {
        'authors': 'Authors',
        'book_authors': 'BookAuthors',
        'book_group_authors': 'BookGroupAuthors'
    }

    def __init__(self, authors=None, book_authors=None, book_group_authors=None):  # noqa: E501
        """Author - a model defined in Swagger"""  # noqa: E501
        self._authors = None
        self._book_authors = None
        self._book_group_authors = None
        self.discriminator = None
        if authors is not None:
            self.authors = authors
        if book_authors is not None:
            self.book_authors = book_authors
        if book_group_authors is not None:
            self.book_group_authors = book_group_authors

    @property
    def authors(self):
        """Gets the authors of this Author.  # noqa: E501


        :return: The authors of this Author.  # noqa: E501
        :rtype: list[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors):
        """Sets the authors of this Author.


        :param authors: The authors of this Author.  # noqa: E501
        :type: list[str]
        """

        self._authors = authors

    @property
    def book_authors(self):
        """Gets the book_authors of this Author.  # noqa: E501


        :return: The book_authors of this Author.  # noqa: E501
        :rtype: list[str]
        """
        return self._book_authors

    @book_authors.setter
    def book_authors(self, book_authors):
        """Sets the book_authors of this Author.


        :param book_authors: The book_authors of this Author.  # noqa: E501
        :type: list[str]
        """

        self._book_authors = book_authors

    @property
    def book_group_authors(self):
        """Gets the book_group_authors of this Author.  # noqa: E501

        Book authors if In case of a book series  # noqa: E501

        :return: The book_group_authors of this Author.  # noqa: E501
        :rtype: list[str]
        """
        return self._book_group_authors

    @book_group_authors.setter
    def book_group_authors(self, book_group_authors):
        """Sets the book_group_authors of this Author.

        Book authors if In case of a book series  # noqa: E501

        :param book_group_authors: The book_group_authors of this Author.  # noqa: E501
        :type: list[str]
        """

        self._book_group_authors = book_group_authors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Author, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Author):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
