# coding: utf-8

"""
    Web of Science API Lite

    A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types.   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WosLiteResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query_result': 'QueryResult',
        'data': 'list[WosLiteRecord]'
    }

    attribute_map = {
        'query_result': 'QueryResult',
        'data': 'Data'
    }

    def __init__(self, query_result=None, data=None):  # noqa: E501
        """WosLiteResponse - a model defined in Swagger"""  # noqa: E501
        self._query_result = None
        self._data = None
        self.discriminator = None
        if query_result is not None:
            self.query_result = query_result
        if data is not None:
            self.data = data

    @property
    def query_result(self):
        """Gets the query_result of this WosLiteResponse.  # noqa: E501


        :return: The query_result of this WosLiteResponse.  # noqa: E501
        :rtype: QueryResult
        """
        return self._query_result

    @query_result.setter
    def query_result(self, query_result):
        """Sets the query_result of this WosLiteResponse.


        :param query_result: The query_result of this WosLiteResponse.  # noqa: E501
        :type: QueryResult
        """

        self._query_result = query_result

    @property
    def data(self):
        """Gets the data of this WosLiteResponse.  # noqa: E501

        The array of the Web of Science records  # noqa: E501

        :return: The data of this WosLiteResponse.  # noqa: E501
        :rtype: list[WosLiteRecord]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this WosLiteResponse.

        The array of the Web of Science records  # noqa: E501

        :param data: The data of this WosLiteResponse.  # noqa: E501
        :type: list[WosLiteRecord]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WosLiteResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WosLiteResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
